const allTasksData = [

            // Exemplo: { date: '2025-08-12', subject: 'Língua Portuguesa', lesson: '1', topic: '...', type: 'video', completed: true },
            
            // --- JUNHO 2025 ---
            { date: '2025-06-24', subject: 'Língua Portuguesa', lesson: '1', topic: 'Panorama das Classes Gramaticais', type: 'video', completed: true },
            { date: '2025-06-24', subject: 'Língua Portuguesa', lesson: '2', topic: 'Panorama das Classes Gramaticais II', type: 'video', completed: true },
            { date: '2025-06-24', subject: 'Língua Portuguesa', lesson: '3', topic: 'Substantivos e seus Satélites', type: 'video', completed: true },
            { date: '2025-06-24', subject: 'Língua Portuguesa', lesson: '4', topic: 'Substantivos e seus Satélites II', type: 'video', completed: true },
            { date: '2025-06-24', subject: 'Raciocínio Lógico-Matemático', lesson: '1', topic: 'Frações', type: 'video', completed: true },
            { date: '2025-06-24', subject: 'Raciocínio Lógico-Matemático', lesson: '2', topic: 'Frações II', type: 'video', completed: true },
            { date: '2025-06-24', subject: 'Raciocínio Lógico-Matemático', lesson: '3', topic: 'Frações III', type: 'video', completed: true },
            { date: '2025-06-24', subject: 'Raciocínio Lógico-Matemático', lesson: '4', topic: 'Dicas para Simplificar ("Cortar" ou Aproximar) Seus Cálculos', type: 'video', completed: true },
            { date: '2025-06-24', subject: 'Administração Pública', lesson: '1', topic: 'Princípios Fundamentais', type: 'video', completed: true },
            { date: '2025-06-25', subject: 'Administração Pública', lesson: '1', topic: 'Princípios Fundamentais', type: 'video', completed: true },
            { date: '2025-06-25', subject: 'Administração Pública', lesson: '2', topic: 'Princípios Fundamentais II', type: 'video', completed: true },
            { date: '2025-06-25', subject: 'Administração Pública', lesson: '3', topic: 'Teoria Geral dos Direitos Fundamentais', type: 'video', completed: true },
            { date: '2025-06-25', subject: 'Administração Pública', lesson: '4', topic: 'Artigo 5º', type: 'video', completed: true },
            { date: '2025-06-25', subject: 'Conhecimentos Específicos', lesson: '1', topic: 'História das Políticas Públicas - Linha do Tempo', type: 'video', completed: true },
            { date: '2025-06-25', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'História das Políticas Públicas - Linha do Tempo II', type: 'video', completed: true },
            { date: '2025-06-25', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'História das Políticas Públicas - Linha do Tempo III', type: 'video', completed: true },
            { date: '2025-06-25', subject: 'Conhecimentos Específicos', lesson: '4', topic: 'História das Políticas Públicas - Linha do Tempo IV', type: 'video', completed: true },
            { date: '2025-06-25', subject: 'Língua Portuguesa', lesson: '5', topic: 'Adjetivos - Identificação, Valor Discursivo', type: 'video', completed: true },
            { date: '2025-06-25', subject: 'Língua Portuguesa', lesson: '6', topic: 'Adjetivos - Flexão', type: 'video', completed: true },
            { date: '2025-06-25', subject: 'Língua Portuguesa', lesson: '7', topic: 'Adjetivos - Locução Adjetiva e Exercícios', type: 'video', completed: true },
            { date: '2025-06-25', subject: 'Língua Portuguesa', lesson: '8', topic: 'Artigo: Identificação, Emprego e Sentido', type: 'video', completed: true },
            { date: '2025-06-26', subject: 'Língua Portuguesa', lesson: '8', topic: 'Artigo: Identificação, Emprego e Sentido', type: 'video', completed: true },
            { date: '2025-06-26', subject: 'Raciocínio Lógico-Matemático', lesson: '5', topic: 'Conjuntos', type: 'video', completed: true },
            { date: '2025-06-26', subject: 'Raciocínio Lógico-Matemático', lesson: '6', topic: 'Conjuntos II', type: 'video', completed: true },
            { date: '2025-06-26', subject: 'Raciocínio Lógico-Matemático', lesson: '7', topic: 'Conjuntos III', type: 'video', completed: true },
            { date: '2025-06-26', subject: 'Raciocínio Lógico-Matemático', lesson: '8', topic: 'Conjuntos IV', type: 'video', completed: true },
            { date: '2025-06-26', subject: 'Administração Pública', lesson: '5', topic: 'Artigo 5º II', type: 'video', completed: true },
            { date: '2025-06-26', subject: 'Administração Pública', lesson: '6', topic: 'Artigo 5º III', type: 'video', completed: true },
            { date: '2025-06-26', subject: 'Administração Pública', lesson: '7', topic: 'Artigo 5º IV', type: 'video', completed: true },
            { date: '2025-06-26', subject: 'Administração Pública', lesson: '8', topic: 'Artigo 5º V', type: 'video', completed: true },
            { date: '2025-06-27', subject: 'Conhecimentos Específicos', lesson: '5', topic: 'História das Políticas Públicas - Linha do Tempo V', type: 'video', completed: true },
            { date: '2025-06-27', subject: 'Conhecimentos Específicos', lesson: '6', topic: 'História das Políticas Públicas - Linha do Tempo VI', type: 'video', completed: true },
            { date: '2025-06-27', subject: 'Conhecimentos Específicos', lesson: '7', topic: 'História das Políticas Públicas - Linha do Tempo VII', type: 'video', completed: true },
            { date: '2025-06-27', subject: 'Língua Portuguesa', lesson: '9', topic: 'Artigo: Identificação, Emprego e Sentido II', type: 'video', completed: true },
            { date: '2025-06-27', subject: 'Língua Portuguesa', lesson: '10', topic: 'Preposições: Identificação, Locução Prepositiva, Valor Semântico', type: 'video', completed: true },
            // --- JULHO 2025 ---
            { date: '2025-07-15', subject: 'Conhecimentos Específicos', lesson: '8', topic: 'História das Políticas Públicas - Linha do Tempo VIII', type: 'video', completed: true },
            { date: '2025-07-15', subject: 'Conhecimentos Específicos', lesson: '9', topic: 'História das Políticas Públicas - Linha do Tempo IX', type: 'video', completed: true },
            { date: '2025-07-15', subject: 'Conhecimentos Específicos', lesson: '10', topic: 'História das Políticas Públicas - Linha do Tempo X', type: 'video', completed: true },
            { date: '2025-07-15', subject: 'Conhecimentos Específicos', lesson: '11', topic: 'Contextualização', type: 'video', completed: true },
            { date: '2025-07-15', subject: 'Língua Portuguesa', lesson: '11', topic: 'Pronomes: Identificação, Emprego de Pronomes Pessoais', type: 'video', completed: true },
            { date: '2025-07-15', subject: 'Língua Portuguesa', lesson: '12', topic: 'Pronomes Possessivos', type: 'video', completed: true },
            { date: '2025-07-15', subject: 'Língua Portuguesa', lesson: '13', topic: 'Pronomes Indefinidos - Pronomes Interrogativos e Pronomes Relativos', type: 'video', completed: true },
            { date: '2025-07-16', subject: 'Língua Portuguesa', lesson: '13', topic: 'Pronomes Indefinidos - Pronomes Interrogativos e Pronomes Relativos', type: 'video', completed: true },
            { date: '2025-07-16', subject: 'Língua Portuguesa', lesson: '14', topic: 'Pronomes Relativos', type: 'video', completed: true },
            { date: '2025-07-16', subject: 'Conhecimentos Específicos', lesson: '1', topic: 'Resolução n. 10/2005 - Código de Ética do Psicólogo', type: 'pdf', completed: true },
            { date: '2025-07-16', subject: 'Língua Portuguesa', lesson: '1', topic: 'Compreensão e Interpretação de Textos', type: 'pdf', completed: true },
            { date: '2025-07-17', subject: 'Língua Portuguesa', lesson: '1', topic: 'Compreensão e Interpretação de Textos', type: 'pdf', completed: true },
            { date: '2025-07-18', subject: 'Língua Portuguesa', lesson: '1', topic: 'Compreensão e Interpretação de Textos', type: 'pdf', completed: true },
            { date: '2025-07-18', subject: 'Conhecimentos Específicos', lesson: '12', topic: 'Emendas Recentes', type: 'video', completed: true },
            { date: '2025-07-18', subject: 'Conhecimentos Específicos', lesson: '13', topic: 'Art. 194', type: 'video', completed: true },
            { date: '2025-07-18', subject: 'Conhecimentos Específicos', lesson: '14', topic: 'Art. 195', type: 'video', completed: true },
            { date: '2025-07-18', subject: 'Conhecimentos Específicos', lesson: '15', topic: 'Art. 196', type: 'video', completed: true },
            { date: '2025-07-18', subject: 'Língua Portuguesa', lesson: '15', topic: 'Pronomes Demonstrativos', type: 'video', completed: true },
            { date: '2025-07-19', subject: 'Língua Portuguesa', lesson: '16', topic: 'Emprego e Colocação Pronominal', type: 'video', completed: true },
            { date: '2025-07-19', subject: 'Língua Portuguesa', lesson: '17', topic: 'Emprego e Colocação Pronominal II', type: 'video', completed: true },
            { date: '2025-07-19', subject: 'Língua Portuguesa', lesson: '18', topic: 'Colocação Pronominal', type: 'video', completed: true },
            { date: '2025-07-19', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'Teorias e Técnicas Psicoterápicas Parte I', type: 'pdf', completed: true },
            { date: '2025-07-20', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'Teorias e Técnicas Psicoterápicas - Parte I', type: 'pdf', completed: true },
            { date: '2025-07-20', subject: 'Língua Portuguesa', lesson: '2', topic: 'Tipologias e Gêneros Textuais', type: 'pdf', completed: true },
            { date: '2025-07-21', subject: 'Língua Portuguesa', lesson: '2', topic: 'Tipologias e Gêneros Textuais', type: 'pdf', completed: true },
            { date: '2025-07-22', subject: 'Língua Portuguesa', lesson: '2', topic: 'Tipologias e Gêneros Textuais', type: 'pdf', completed: true },
            { date: '2025-07-22', subject: 'Conhecimentos Específicos', lesson: '16', topic: 'Art. 197', type: 'video', completed: true },
            { date: '2025-07-22', subject: 'Conhecimentos Específicos', lesson: '17', topic: 'Art. 198', type: 'video', completed: true },
            { date: '2025-07-22', subject: 'Conhecimentos Específicos', lesson: '18', topic: 'Art. 198 - Questões', type: 'video', completed: true },
            { date: '2025-07-22', subject: 'Conhecimentos Específicos', lesson: '19', topic: 'Art. 199', type: 'video', completed: true },
            { date: '2025-07-22', subject: 'Língua Portuguesa', lesson: '19', topic: 'Verbos: Definição e Estrutura - Tempos e Modos Verbais - Verbos Regulares', type: 'video', completed: true },
            { date: '2025-07-22', subject: 'Língua Portuguesa', lesson: '20', topic: 'Tempos e Modos Verbais - Verbos Irregulares', type: 'video', completed: true },
            { date: '2025-07-23', subject: 'Língua Portuguesa', lesson: '20', topic: 'Tempos e Modos Verbais - Verbos Irregulares', type: 'video', completed: true },
            { date: '2025-07-23', subject: 'Língua Portuguesa', lesson: '21', topic: 'Tempos e Modos Verbais - Significados', type: 'video', completed: true },
            { date: '2025-07-23', subject: 'Língua Portuguesa', lesson: '22', topic: 'Tempos e Modos Verbais - Significados II', type: 'video', completed: true },
            { date: '2025-07-23', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'Teorias e Técnicas Psicoterápicas - Parte II', type: 'pdf', completed: true },
            { date: '2025-07-24', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'Teorias e Técnicas Psicoterápicas Parte II', type: 'pdf', completed: true },
            { date: '2025-07-24', subject: 'Língua Portuguesa', lesson: '3', topic: 'Coesão e Coerência, Semântica, Figuras e Vícios de Linguagem, Reescrita', type: 'pdf', completed: true },
            { date: '2025-07-25', subject: 'Língua Portuguesa', lesson: '3', topic: 'Coesão e Coerência, Semântica, Figuras e Vícios de Linguagem, Reescrita', type: 'pdf', completed: true },
            { date: '2025-07-25', subject: 'Conhecimentos Específicos', lesson: '20', topic: 'Art. 200', type: 'video', completed: true },
            { date: '2025-07-25', subject: 'Conhecimentos Específicos', lesson: '21', topic: 'Questões Constituição', type: 'video', completed: true },
            { date: '2025-07-25', subject: 'Conhecimentos Específicos', lesson: '22', topic: 'Lei 8.080/90 - Art. 1 a 3', type: 'video', completed: true },
            { date: '2025-07-25', subject: 'Conhecimentos Específicos', lesson: '23', topic: 'Lei 8.080/90 - Art. 4 e Questões', type: 'video', completed: true },
            { date: '2025-07-25', subject: 'Língua Portuguesa', lesson: '23', topic: 'Modo Imperativo', type: 'video', completed: true },
            { date: '2025-07-25', subject: 'Língua Portuguesa', lesson: '24', topic: 'Formas Nominais dos Verbos', type: 'video', completed: true },
            { date: '2025-07-26', subject: 'Língua Portuguesa', lesson: '24', topic: 'Formas Nominais dos Verbos', type: 'video', completed: true },
            { date: '2025-07-26', subject: 'Língua Portuguesa', lesson: '25', topic: 'Classificando Verbos', type: 'video', completed: true },
            { date: '2025-07-26', subject: 'Língua Portuguesa', lesson: '26', topic: 'Correlação Verbal', type: 'video', completed: true },
            { date: '2025-07-26', subject: 'Conhecimentos Específicos', lesson: '4', topic: 'Psicopatologia - Parte I', type: 'pdf', completed: true },
            { date: '2025-07-27', subject: 'Conhecimentos Específicos', lesson: '4', topic: 'Psicopatologia - Parte I', type: 'pdf', completed: true },
            { date: '2025-07-27', subject: 'Língua Portuguesa', lesson: '1', topic: 'Estrutura e Processos de Formação de Palavras', type: 'pdf', completed: true },
            { date: '2025-07-27', subject: 'Conhecimentos Específicos', lesson: '24', topic: 'Lei 8.080/90 - Art. 5º e 6º', type: 'video', completed: true },
            { date: '2025-07-28', subject: 'Conhecimentos Específicos', lesson: '24', topic: 'Lei 8.080/90 - Art. 5º e 6º', type: 'video', completed: true },
            { date: '2025-07-28', subject: 'Conhecimentos Específicos', lesson: '25', topic: 'Lei 8.080/90 - Assistência Toxicológica', type: 'video', completed: true },
            { date: '2025-07-28', subject: 'Conhecimentos Específicos', lesson: '26', topic: 'Lei 8.080/90 - Questões', type: 'video', completed: true },
            { date: '2025-07-28', subject: 'Conhecimentos Específicos', lesson: '27', topic: 'Lei 8.080/90 - Art. 7º e Questões', type: 'video', completed: true },
            { date: '2025-07-28', subject: 'Língua Portuguesa', lesson: '27', topic: 'Vozes Verbais', type: 'video', completed: true },
            { date: '2025-07-28', subject: 'Língua Portuguesa', lesson: '28', topic: 'Vozes Verbais II', type: 'video', completed: true },
            { date: '2025-07-28', subject: 'Língua Portuguesa', lesson: '29', topic: 'Advérbio', type: 'video', completed: true },
            { date: '2025-07-29', subject: 'Língua Portuguesa', lesson: '29', topic: 'Advérbio', type: 'video', completed: true },
            { date: '2025-07-29', subject: 'Língua Portuguesa', lesson: '30', topic: 'Preposições - Numerais e interjeições', type: 'video', completed: true },
            { date: '2025-07-29', subject: 'Conhecimentos Específicos', lesson: '5', topic: 'Psicopatologia - Parte II', type: 'pdf', completed: true },
            { date: '2025-07-29', subject: 'Língua Portuguesa', lesson: '2', topic: 'Emprego e Sentido das Classes Gramaticais - Parte I', type: 'pdf', completed: true },
            { date: '2025-07-30', subject: 'Língua Portuguesa', lesson: '2', topic: 'Emprego e Sentido das Classes Gramaticais - Parte I', type: 'pdf', completed: true },
            { date: '2025-07-31', subject: 'Língua Portuguesa', lesson: '2', topic: 'Emprego e Sentido das Classes Gramaticais - Parte I', type: 'pdf', completed: true },
            { date: '2025-07-31', subject: 'Conhecimentos Específicos', lesson: '28', topic: 'Lei 8.080/90 - Art. 8° a 14', type: 'video', completed: true },
            { date: '2025-07-31', subject: 'Conhecimentos Específicos', lesson: '29', topic: 'Lei 8.080/90 - Questões', type: 'video', completed: true },
            { date: '2025-07-31', subject: 'Conhecimentos Específicos', lesson: '30', topic: 'Lei 8.080/90 - Art. 15', type: 'video', completed: true },
            { date: '2025-07-31', subject: 'Conhecimentos Específicos', lesson: '31', topic: 'Lei 8.080/90 - Art. 16 e Questões', type: 'video', completed: true },
            { date: '2025-07-31', subject: 'Língua Portuguesa', lesson: '1', topic: 'Sintaxe da Oração: Frase, Período e Oração', type: 'video', completed: true },
            { date: '2025-07-31', subject: 'Língua Portuguesa', lesson: '2', topic: 'Sintaxe da Oração: Sujeito', type: 'video', completed: true },
            { date: '2025-07-31', subject: 'Língua Portuguesa', lesson: '3', topic: 'Sintaxe da Oração: Sujeito II', type: 'video', completed: true },
            { date: '2025-07-31', subject: 'Língua Portuguesa', lesson: '4', topic: 'Sintaxe da Oração: Sujeito III', type: 'video', completed: true },
            // --- AGOSTO 2025 ---
            { date: '2025-08-01', subject: 'Língua Portuguesa', lesson: '4', topic: 'Sintaxe da Oração: Sujeito III', type: 'video', completed: true },
            { date: '2025-08-01', subject: 'Conhecimentos Específicos', lesson: '6', topic: 'Psicologia Educacional', type: 'pdf', completed: true },
            { date: '2025-08-01', subject: 'Língua Portuguesa', lesson: '3', topic: 'Emprego e Sentido das Classes Gramaticais - Parte II', type: 'pdf', completed: true },
            { date: '2025-08-02', subject: 'Língua Portuguesa', lesson: '3', topic: 'Emprego e Sentido das Classes Gramaticais - Parte II', type: 'pdf', completed: true },
            { date: '2025-08-03', subject: 'Língua Portuguesa', lesson: '3', topic: 'Emprego e Sentido das Classes Gramaticais - Parte II', type: 'pdf', completed: true },
            { date: '2025-08-03', subject: 'Conhecimentos Específicos', lesson: '32', topic: 'Lei 8.080/90 - Art. 17 e Questões', type: 'video', completed: true },
            { date: '2025-08-03', subject: 'Conhecimentos Específicos', lesson: '33', topic: 'Lei 8.080/90 - Art. 18 e Questões', type: 'video', completed: true },
            { date: '2025-08-03', subject: 'Conhecimentos Específicos', lesson: '34', topic: 'Lei 8.080/90 - Art. 19 ao 19 L', type: 'video', completed: true },
            { date: '2025-08-03', subject: 'Conhecimentos Específicos', lesson: '35', topic: 'Lei 8.080/90 - Art. 19 M ao 19 U', type: 'video', completed: true },
            { date: '2025-08-03', subject: 'Língua Portuguesa', lesson: '5', topic: 'Sintaxe da Oração: Predicativo Versus Aposto', type: 'video', completed: true },
            { date: '2025-08-03', subject: 'Língua Portuguesa', lesson: '6', topic: 'Sintaxe da Oração: Predicativo Versus Aposto II', type: 'video', completed: true },
            { date: '2025-08-03', subject: 'Língua Portuguesa', lesson: '7', topic: 'Sintaxe da Oração: Adjunto Adnominal Versus Predicativo', type: 'video', completed: true },
            { date: '2025-08-04', subject: 'Língua Portuguesa', lesson: '7', topic: 'Sintaxe da Oração: Adjunto Adnominal Versus Predicativo', type: 'video', completed: true },
            { date: '2025-08-04', subject: 'Língua Portuguesa', lesson: '8', topic: 'Sintaxe da Oração: Predicativo Versus Adjunto Adverbial', type: 'video', completed: true },
            { date: '2025-08-04', subject: 'Conhecimentos Específicos', lesson: '7', topic: 'Lei Federal n. 10.741/2003 - Estatuto da Pessoa Idosa', type: 'pdf', completed: true },
            { date: '2025-08-04', subject: 'Língua Portuguesa', lesson: '4', topic: 'A Sintaxe do Período Simples - Parte I', type: 'pdf', completed: true },
            { date: '2025-08-05', subject: 'Língua Portuguesa', lesson: '4', topic: 'A Sintaxe do Período Simples - Parte I', type: 'pdf', completed: true },
            { date: '2025-08-05', subject: 'Conhecimentos Específicos', lesson: '36', topic: 'Lei 8.080/90 - Questões', type: 'video', completed: true },
            { date: '2025-08-06', subject: 'Conhecimentos Específicos', lesson: '36', topic: 'Lei 8.080/90 - Questões', type: 'video', completed: true },
            { date: '2025-08-06', subject: 'Conhecimentos Específicos', lesson: '37', topic: 'Lei 8.080/90 - Art. 20 ao 35', type: 'video', completed: true },
            { date: '2025-08-06', subject: 'Conhecimentos Específicos', lesson: '38', topic: 'Lei 8.080/90 - Art. 36 ao 55', type: 'video', completed: true },
            { date: '2025-08-06', subject: 'Conhecimentos Específicos', lesson: '39', topic: 'Lei 8.080/90 - Questões', type: 'video', completed: true },
            { date: '2025-08-06', subject: 'Língua Portuguesa', lesson: '9', topic: 'Sintaxe da Oração: Adjunto Adnominal Versus Adjunto Adverbial', type: 'video', completed: true },
            { date: '2025-08-06', subject: 'Língua Portuguesa', lesson: '10', topic: 'Sintaxe da Oração: Adjunto Adverbial Versus Objeto', type: 'video', completed: true },
            { date: '2025-08-06', subject: 'Língua Portuguesa', lesson: '11', topic: 'Sintaxe da Oração: Adjunto Adverbial Versus Objeto', type: 'video', completed: true },
            { date: '2025-08-06', subject: 'Língua Portuguesa', lesson: '12', topic: 'Sintaxe da Oração: Complemento Nominal Versus Adjunto Adnominal', type: 'video', completed: true },
            { date: '2025-08-07', subject: 'Língua Portuguesa', lesson: '12', topic: 'Sintaxe da Oração: Complemento Nominal Versus Adjunto Adnominal', type: 'video', completed: true },
            { date: '2025-08-07', subject: 'Conhecimentos Específicos', lesson: '8', topic: 'Lei n. 13.146/2015 e Alterações - Estatuto da Pessoa com Deficiência', type: 'pdf' },
            { date: '2025-08-07', subject: 'Língua Portuguesa', lesson: '5', topic: 'A Sintaxe do Período Simples - Parte II', type: 'pdf', completed: true },
            { date: '2025-08-08', subject: 'Língua Portuguesa', lesson: '5', topic: 'A Sintaxe do Período Simples - Parte II', type: 'pdf', completed: true },
            { date: '2025-08-08', subject: 'Conhecimentos Específicos', lesson: '40', topic: 'Alocação de Recursos - Como Consta na Legislação - CF e Lei 8.080/90', type: 'video', completed: true },
            { date: '2025-08-08', subject: 'Conhecimentos Específicos', lesson: '41', topic: 'Lei Orgânica da Saúde - Lei 8.142/90', type: 'video', completed: true },
            { date: '2025-08-09', subject: 'Conhecimentos Específicos', lesson: '41', topic: 'Lei Orgânica da Saúde - Lei 8.142/90', type: 'video', completed: true },
            { date: '2025-08-09', subject: 'Conhecimentos Específicos', lesson: '42', topic: 'Lei Orgânica da Saúde - Lei 8.142/90-Questões', type: 'video', completed: true },
            { date: '2025-08-09', subject: 'Conhecimentos Específicos', lesson: '43', topic: 'Decreto 7.508/11 - Arts. 1 e 2', type: 'video', completed: true },
            { date: '2025-08-09', subject: 'Língua Portuguesa', lesson: '13', topic: 'Verbos de Ligação e Transitividade Verbal', type: 'video', completed: true },
            { date: '2025-08-09', subject: 'Língua Portuguesa', lesson: '14', topic: 'Adjunto Adnominal Versus Predicativo do Objeto e Tipos de Predicado', type: 'video', completed: true },
            { date: '2025-08-09', subject: 'Língua Portuguesa', lesson: '15', topic: 'Tipos de Predicado', type: 'video', completed: true },
            { date: '2025-08-10', subject: 'Língua Portuguesa', lesson: '15', topic: 'Tipos de Predicado', type: 'video', completed: true },
            { date: '2025-08-10', subject: 'Língua Portuguesa', lesson: '16', topic: 'Aposto Versus Vocativo', type: 'video', completed: true },
            { date: '2025-08-10', subject: 'Conhecimentos Específicos', lesson: '9', topic: 'Psicologia Social', type: 'pdf' },
            { date: '2025-08-10', subject: 'Língua Portuguesa', lesson: '6', topic: 'A Sintaxe do Período Composto', type: 'pdf' },
            { date: '2025-08-11', subject: 'Língua Portuguesa', lesson: '6', topic: 'A Sintaxe do Período Composto', type: 'pdf' },
            { date: '2025-08-12', subject: 'Língua Portuguesa', lesson: '6', topic: 'A Sintaxe do Período Composto', type: 'pdf' },
            { date: '2025-08-12', subject: 'Conhecimentos Específicos', lesson: '44', topic: 'Decreto 7.508/11 - Questões - Parte 1', type: 'video', completed: true },
            { date: '2025-08-12', subject: 'Conhecimentos Específicos', lesson: '45', topic: 'Decreto 7.508/11 - Arts. 3 a 7', type: 'video', completed: true },
            { date: '2025-08-12', subject: 'Conhecimentos Específicos', lesson: '46', topic: 'Decreto 7.508/11 - Questões - Parte 2', type: 'video', completed: true },
            { date: '2025-08-12', subject: 'Conhecimentos Específicos', lesson: '47', topic: 'Decreto 7.508/11 - Arts. 8 a 14', type: 'video', completed: true },
            { date: '2025-08-12', subject: 'Língua Portuguesa', lesson: '17', topic: 'Funções Sintáticas dos Pronomes Pessoais Oblíquos', type: 'video' },
            { date: '2025-08-12', subject: 'Língua Portuguesa', lesson: '1', topic: 'Regência Verbal e Nominal', type: 'video' },
            { date: '2025-08-12', subject: 'Língua Portuguesa', lesson: '2', topic: 'Regência Verbal e Nominal II', type: 'video' },
            { date: '2025-08-12', subject: 'Língua Portuguesa', lesson: '3', topic: 'Regência Verbal e Nominal III', type: 'video' },
            { date: '2025-08-13', subject: 'Língua Portuguesa', lesson: '3', topic: 'Regência Verbal e Nominal III', type: 'video' },
            { date: '2025-08-13', subject: 'Conhecimentos Específicos', lesson: '10', topic: 'Avaliação Psicológica - Parte I', type: 'pdf' },
            { date: '2025-08-13', subject: 'Língua Portuguesa', lesson: '7', topic: 'Concordância, Regência, Colocação, Crase e Pontuação', type: 'pdf' },
            { date: '2025-08-14', subject: 'Língua Portuguesa', lesson: '7', topic: 'Concordância, Regência, Colocação, Crase e Pontuação', type: 'pdf' },
            { date: '2025-08-14', subject: 'Conhecimentos Específicos', lesson: '48', topic: 'Decreto 7.508/11 - Questões', type: 'video' },
            { date: '2025-08-14', subject: 'Conhecimentos Específicos', lesson: '49', topic: 'Decreto 7.508/11 - Arts. 15 ao 25', type: 'video' },
            { date: '2025-08-15', subject: 'Conhecimentos Específicos', lesson: '49', topic: 'Decreto 7.508/11 - Arts. 15 ao 25', type: 'video' },
            { date: '2025-08-15', subject: 'Conhecimentos Específicos', lesson: '50', topic: 'Decreto 7.508/11 - Arts. 26 a 30', type: 'video' },
            { date: '2025-08-15', subject: 'Conhecimentos Específicos', lesson: '51', topic: 'Decreto 7.508/11 - Arts. 31 a 44', type: 'video' },
            { date: '2025-08-15', subject: 'Língua Portuguesa', lesson: '1', topic: 'Emprego do Sinal Indicativo de Crase', type: 'video' },
            { date: '2025-08-15', subject: 'Língua Portuguesa', lesson: '2', topic: 'Emprego do Sinal Indicativo de Crase II', type: 'video' },
            { date: '2025-08-15', subject: 'Língua Portuguesa', lesson: '3', topic: 'Emprego do Sinal Indicativo de Crase III', type: 'video' },
            { date: '2025-08-15', subject: 'Língua Portuguesa', lesson: '1', topic: 'Coordenação Vs Subordinação', type: 'video' },
            { date: '2025-08-16', subject: 'Língua Portuguesa', lesson: '1', topic: 'Coordenação Vs Subordinação', type: 'video' },
            { date: '2025-08-16', subject: 'Conhecimentos Específicos', lesson: '11', topic: 'Avaliação Psicológica – Parte II', type: 'pdf' },
            { date: '2025-08-17', subject: 'Conhecimentos Específicos', lesson: '11', topic: 'Avaliação Psicológica – Parte II', type: 'pdf' },
            { date: '2025-08-17', subject: 'Conhecimentos Específicos', lesson: '52', topic: 'Decreto 7.508/11 - Questões', type: 'video' },
            { date: '2025-08-17', subject: 'Conhecimentos Específicos', lesson: '53', topic: 'Decreto 7.508/11 - Questões II', type: 'video' },
            { date: '2025-08-17', subject: 'Conhecimentos Específicos', lesson: '54', topic: 'Decreto 7.508/11 - Questões III', type: 'video' },
            { date: '2025-08-17', subject: 'Conhecimentos Específicos', lesson: '1', topic: 'Estatuto do Idoso - Lei nº 10.741/2003 I', type: 'video' },
            { date: '2025-08-17', subject: 'Língua Portuguesa', lesson: '2', topic: 'Período Composto - Oração Subordinada Adjetiva', type: 'video' },
            { date: '2025-08-17', subject: 'Língua Portuguesa', lesson: '3', topic: 'Período Composto - Oração Subordinada Adjetiva e Função Sintática do Pronome Relativo', type: 'video' },
            { date: '2025-08-17', subject: 'Língua Portuguesa', lesson: '4', topic: 'Período Composto - Oração Subordinada Substantiva', type: 'video' },
            { date: '2025-08-18', subject: 'Língua Portuguesa', lesson: '4', topic: 'Período Composto - Oração Subordinada Substantiva', type: 'video' },
            { date: '2025-08-18', subject: 'Língua Portuguesa', lesson: '5', topic: 'Período Composto - Oração Subordinada Adverbial', type: 'video' },
            { date: '2025-08-18', subject: 'Conhecimentos Específicos', lesson: '12', topic: 'Psicologia da Saúde e Intervenções', type: 'pdf' },
            { date: '2025-08-18', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'Estatuto do Idoso - Lei nº 10.741/2003 II', type: 'video' },
            { date: '2025-08-18', subject: 'Raciocínio Lógico-Matemático', lesson: '1', topic: 'Operadores Lógicos Fundamentais', type: 'pdf' },
            { date: '2025-08-19', subject: 'Raciocínio Lógico-Matemático', lesson: '1', topic: 'Operadores Lógicos Fundamentais', type: 'pdf' },
            { date: '2025-08-19', subject: 'Administração Pública', lesson: '1', topic: 'Princípios Fundamentais', type: 'pdf' },
            { date: '2025-08-19', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'Estatuto do Idoso - Lei nº 10.741/2003 II', type: 'video' },
            { date: '2025-08-19', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'Estatuto do Idoso - Lei nº 10.741/2003 III', type: 'video' },
            { date: '2025-08-19', subject: 'Conhecimentos Específicos', lesson: '4', topic: 'Estatuto do Idoso - Lei nº 10.741/2003 IV', type: 'video' },
            { date: '2025-08-19', subject: 'Conhecimentos Específicos', lesson: '5', topic: 'Estatuto do Idoso - Lei nº 10.741/2003 V', type: 'video' },
            { date: '2025-08-19', subject: 'Língua Portuguesa', lesson: '6', topic: 'Período Composto - Oração Subordinada Adverbial II', type: 'video' },
            { date: '2025-08-19', subject: 'Língua Portuguesa', lesson: '7', topic: 'Período Composto - Orações Reduzidas', type: 'video' },
            { date: '2025-08-19', subject: 'Língua Portuguesa', lesson: '8', topic: 'Período Composto - Orações Coordenadas', type: 'video' },
            { date: '2025-08-20', subject: 'Administração Pública', lesson: '1', topic: 'Princípios Fundamentais', type: 'pdf' },
            { date: '2025-08-20', subject: 'Raciocínio Lógico-Matemático', lesson: '2', topic: 'Operador Condicional', type: 'pdf' },
            { date: '2025-08-20', subject: 'Língua Portuguesa', lesson: '8', topic: 'Período Composto - Orações Coordenadas', type: 'video' },
            { date: '2025-08-20', subject: 'Língua Portuguesa', lesson: '9', topic: 'Período Composto - Orações Coordenadas II', type: 'video' },
            { date: '2025-08-20', subject: 'Conhecimentos Específicos', lesson: '13', topic: 'Psicologia Organizacional - Parte I', type: 'pdf' },
            { date: '2025-08-21', subject: 'Raciocínio Lógico-Matemático', lesson: '2', topic: 'Operador Condicional', type: 'pdf' },
            { date: '2025-08-21', subject: 'Conhecimentos Específicos', lesson: '13', topic: 'Psicologia Organizacional - Parte I', type: 'pdf' },
            { date: '2025-08-21', subject: 'Conhecimentos Específicos', lesson: '6', topic: 'Estatuto do Idoso - Lei nº 10.741/2003 VI', type: 'video' },
            { date: '2025-08-21', subject: 'Conhecimentos Específicos', lesson: '7', topic: 'Estatuto do Idoso - Lei nº 10.741/2003 VII', type: 'video' },
            { date: '2025-08-21', subject: 'Conhecimentos Específicos', lesson: '8', topic: 'Estatuto do Idoso - Lei nº 10.741/2003-Resumo e Jurisprudência', type: 'video' },
            { date: '2025-08-21', subject: 'Conhecimentos Específicos', lesson: '9', topic: 'Estatuto do Idoso - Lei nº 10.741/2003 - Exercícios', type: 'video' },
            { date: '2025-08-21', subject: 'Língua Portuguesa', lesson: '10', topic: 'Funções do SE', type: 'video' },
            { date: '2025-08-21', subject: 'Língua Portuguesa', lesson: '1', topic: 'Pontuação', type: 'video' },
            { date: '2025-08-22', subject: 'Raciocínio Lógico-Matemático', lesson: '2', topic: 'Operador Condicional', type: 'pdf' },
            { date: '2025-08-22', subject: 'Administração Pública', lesson: '2', topic: 'Direitos e Deveres Individuais e Coletivos', type: 'pdf' },
            { date: '2025-08-22', subject: 'Língua Portuguesa', lesson: '1', topic: 'Pontuação', type: 'video' },
            { date: '2025-08-22', subject: 'Língua Portuguesa', lesson: '2', topic: 'Pontuação II', type: 'video' },
            { date: '2025-08-22', subject: 'Língua Portuguesa', lesson: '3', topic: 'Pontuação III', type: 'video' },
            { date: '2025-08-22', subject: 'Conhecimentos Específicos', lesson: '14', topic: 'Psicologia Organizacional - Parte II', type: 'pdf' },
            { date: '2025-08-23', subject: 'Conhecimentos Específicos', lesson: '14', topic: 'Psicologia Organizacional - Parte II', type: 'pdf' },
            { date: '2025-08-23', subject: 'Conhecimentos Específicos', lesson: '10', topic: 'Estatuto do Idoso - Lei nº 10.741/2003 - Exercícios II', type: 'video' },
            { date: '2025-08-23', subject: 'Conhecimentos Específicos', lesson: '1', topic: 'Lei nº 13.146/15 - Livro I - Parte Geral - Título I - Disposições Preliminares - Capítulo 1 - Disposições Gerais', type: 'video' },
            { date: '2025-08-23', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'Lei nº 13.146/15- Livro I - Parte Geral - Titulo I - Disposições Preliminares - Capitulo I - Disposições Gerais', type: 'video' },
            { date: '2025-08-23', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'Lei nº 13.146/15- Livro I - Parte Geral - Título I - Disposições Preliminares - Capítulo II - da Igualdade e da Não Discriminação', type: 'video' },
            { date: '2025-08-23', subject: 'Língua Portuguesa', lesson: '4', topic: 'Pontuação IV', type: 'video' },
            { date: '2025-08-23', subject: 'Língua Portuguesa', lesson: '1', topic: 'Concordância Verbal', type: 'video' },
            { date: '2025-08-24', subject: 'Língua Portuguesa', lesson: '1', topic: 'Concordância Verbal', type: 'video' },
            { date: '2025-08-24', subject: 'Língua Portuguesa', lesson: '2', topic: 'Concordância Verbal II', type: 'video' },
            { date: '2025-08-24', subject: 'Língua Portuguesa', lesson: '3', topic: 'Concordância Verbal III', type: 'video' },
            { date: '2025-08-24', subject: 'Conhecimentos Específicos', lesson: '15', topic: 'Gestão de Pessoas nas Organizações Públicas e Privadas', type: 'pdf' },
            { date: '2025-08-25', subject: 'Administração Pública', lesson: '2', topic: 'Direitos e Deveres Individuais e Coletivos', type: 'pdf' },
            { date: '2025-08-25', subject: 'Conhecimentos Específicos', lesson: '15', topic: 'Gestão de Pessoas nas Organizações Públicas e Privadas', type: 'pdf' },
            { date: '2025-08-25', subject: 'Conhecimentos Específicos', lesson: '4', topic: 'Lei nº 13.146/15- Livro I - Parte Geral - Titulo II - dos Direitos Fundamentais - Capítulo I do Direito à Vida e Capítulo II - do Direito à Habilitação e à Reabilitação', type: 'video' },
            { date: '2025-08-25', subject: 'Conhecimentos Específicos', lesson: '5', topic: 'Lei nº 13.146/15 - Livro I - Parte Geral - Titulo II - dos Direitos Fundamentais - Capitulo III - do Direito à Saúde', type: 'video' },
            { date: '2025-08-25', subject: 'Conhecimentos Específicos', lesson: '6', topic: 'Lei nº 13.146/15- Livro I - Parte Geral - Título II - Dos Direitos Fundamentais - Capítulo IV - do Direito à Educação', type: 'video' },
            { date: '2025-08-25', subject: 'Conhecimentos Específicos', lesson: '7', topic: 'Lei nº 13.146/15 - Livro I - Parte Geral - Título II - dos Direitos Fundamentais - Capitulo V e Vil - do Direito à Moradia e Direito ao Trabalho', type: 'video' },
            { date: '2025-08-25', subject: 'Língua Portuguesa', lesson: '4', topic: 'Concordância Nominal', type: 'video' },
            { date: '2025-08-26', subject: 'Administração Pública', lesson: '2', topic: 'Direitos e Deveres Individuais e Coletivos', type: 'pdf' },
            { date: '2025-08-26', subject: 'Raciocínio Lógico-Matemático', lesson: '3', topic: 'Lógica de Argumentação', type: 'pdf' },
            { date: '2025-08-26', subject: 'Língua Portuguesa', lesson: '4', topic: 'Concordância Nominal', type: 'video' },
            { date: '2025-08-26', subject: 'Língua Portuguesa', lesson: '1', topic: 'Significação Literal e Contextual', type: 'video' },
            { date: '2025-08-26', subject: 'Língua Portuguesa', lesson: '2', topic: 'Campos Semânticos e Campos Lexicais', type: 'video' },
            { date: '2025-08-26', subject: 'Língua Portuguesa', lesson: '1', topic: 'Figuras de Linguagem - Denotação, Conotação, Figurativização, Linguagem Lógica e Figurada', type: 'video' },
            { date: '2025-08-26', subject: 'Conhecimentos Específicos', lesson: '16', topic: 'Psicodinâmica do Trabalho', type: 'pdf' },
            { date: '2025-08-27', subject: 'Administração Pública', lesson: '3', topic: 'Direitos Sociais', type: 'pdf' },
            { date: '2025-08-27', subject: 'Raciocínio Lógico-Matemático', lesson: '3', topic: 'Lógica de Argumentação', type: 'pdf' },
            { date: '2025-08-27', subject: 'Conhecimentos Específicos', lesson: '16', topic: 'Psicodinâmica do Trabalho', type: 'pdf' },
            { date: '2025-08-27', subject: 'Conhecimentos Específicos', lesson: '8', topic: 'Lei nº 13.146/15 - Livro I - Parte Geral - Titulo II - dos Direitos Fundamentais - Capítulo VII, VIII, IX e X - V - Direito à Assistência e Previdência Social do Direito', type: 'video' },
            { date: '2025-08-27', subject: 'Conhecimentos Específicos', lesson: '9', topic: 'Lei nº 13.146/15- Livro I - Parte Geral - Titulo III - da Acessibilidade - Capítulo I - Disposições Gerais e do Acesso à Informação e à Comunicação', type: 'video' },
            { date: '2025-08-27', subject: 'Conhecimentos Específicos', lesson: '10', topic: 'Lei nº 13.146/15 - Livro I - Parte Geral - Titulo III - Capítulos II e III - Do Acesso à Informação e à Comunicação e Da Tecnologia Assistiva', type: 'video' },
            { date: '2025-08-27', subject: 'Conhecimentos Específicos', lesson: '11', topic: 'Lei nº 13.146/15 - Livro I - Parte Geral - Título III - Capítulos IV e Titulo IV - Do Direito à Participação na Vida Pública e Política e da Tecnologia Assisti', type: 'video' },
            { date: '2025-08-27', subject: 'Língua Portuguesa', lesson: '2', topic: 'Figuras de Linguagem - Denotação, Conotação, Figurativização, Linguagem Lógica e Figurada II', type: 'video' },
            { date: '2025-08-27', subject: 'Língua Portuguesa', lesson: '3', topic: 'Figuras de Linguagem - Denotação, Conotação, Figurativização, Linguagem Lógica e Figurada III', type: 'video' },
            { date: '2025-08-28', subject: 'Administração Pública', lesson: '3', topic: 'Direitos Sociais', type: 'pdf' },
            { date: '2025-08-28', subject: 'Língua Portuguesa', lesson: '3', topic: 'Figuras de Linguagem - Denotação, Conotação, Figurativização, Linguagem Lógica e Figurada III', type: 'video' },
            { date: '2025-08-28', subject: 'Língua Portuguesa', lesson: '1', topic: 'Compreensão e Interpretação', type: 'video' },
            { date: '2025-08-28', subject: 'Língua Portuguesa', lesson: '1', topic: 'Tipologia e Gêneros Textuais - Modos de Organização Discursiva', type: 'video' },
            { date: '2025-08-28', subject: 'Conhecimentos Específicos', lesson: '17', topic: 'Lei Federal n. 8.069/1990 - Estatuto da Criança e do Adolescente - Parte Geral', type: 'pdf' },
            { date: '2025-08-29', subject: 'Administração Pública', lesson: '3', topic: 'Direitos Sociais', type: 'pdf' },
            { date: '2025-08-29', subject: 'Raciocínio Lógico-Matemático', lesson: '4', topic: 'Razão e Proporção, Regra de Três e Porcentagem', type: 'pdf' },
            { date: '2025-08-29', subject: 'Conhecimentos Específicos', lesson: '17', topic: 'Lei Federal n. 8.069/1990 - Estatuto da Criança e do Adolescente - Parte Geral', type: 'pdf' },
            { date: '2025-08-29', subject: 'Conhecimentos Específicos', lesson: '12', topic: 'Lei nº 13.146/15 - Livro II - Parte Especial - Título 1 - Do Acesso à Justiça - Capítulo I e II - Disposições Gerais e Do Reconhecimento Igual Perante a Lei', type: 'video' },
            { date: '2025-08-29', subject: 'Conhecimentos Específicos', lesson: '13', topic: 'Lei nº 13.146/15 - Livro II - Parte Especial - Título II - Dos Crimes e das Infrações Administrativas', type: 'video' },
            { date: '2025-08-30', subject: 'Conhecimentos Específicos', lesson: '13', topic: 'Lei nº 13.146/15 - Livro II - Parte Especial - Título II - Dos Crimes e das Infrações Administrativas', type: 'video' },
            { date: '2025-08-30', subject: 'Conhecimentos Específicos', lesson: '14', topic: 'Lei nº 13.146/15 - Livro II - Parte Especial - Título III - Disposições Finais e Transitórias', type: 'video' },
            { date: '2025-08-30', subject: 'Conhecimentos Específicos', lesson: '15', topic: 'Lei nº 13.146/15 - Livro II - Parte Especial - Título III - Disposições Finais e Transitórias II', type: 'video' },
            { date: '2025-08-30', subject: 'Língua Portuguesa', lesson: '2', topic: 'Tipologia e Gêneros Textuais - Modos de Organização Discursiva II', type: 'video' },
            { date: '2025-08-30', subject: 'Língua Portuguesa', lesson: '3', topic: 'Tipos de Discurso - Direto, Indireto, Indireto Livre', type: 'video' },
            { date: '2025-08-30', subject: 'Língua Portuguesa', lesson: '1', topic: 'A Coerência Textual', type: 'video' },
            { date: '2025-08-31', subject: 'Língua Portuguesa', lesson: '1', topic: 'A Coerência Textual', type: 'video' },
            { date: '2025-08-31', subject: 'Língua Portuguesa', lesson: '2', topic: 'Mecanismos de Coesão Textual', type: 'video' },
            { date: '2025-08-31', subject: 'Conhecimentos Específicos', lesson: '18', topic: 'Lei Federal n. 8.069/1990 - Estatuto da Criança e do Adolescente - Parte Especial', type: 'pdf' },
            // --- SETEMBRO 2025 ---
            { date: '2025-09-01', subject: 'Raciocínio Lógico-Matemático', lesson: '4', topic: 'Razão e Proporção, Regra de Três e Porcentagem', type: 'pdf' },
            { date: '2025-09-01', subject: 'Administração Pública', lesson: '4', topic: 'Nacionalidade', type: 'pdf' },
            { date: '2025-09-01', subject: 'Conhecimentos Específicos', lesson: '18', topic: 'Lei Federal n. 8.069/1990 - Estatuto da Criança e do Adolescente - Parte Especial', type: 'pdf' },
            { date: '2025-09-01', subject: 'Conhecimentos Específicos', lesson: '16', topic: 'Lei nº 13.146/15 - Exercícios', type: 'video' },
            { date: '2025-09-02', subject: 'Administração Pública', lesson: '4', topic: 'Nacionalidade', type: 'pdf' },
            { date: '2025-09-02', subject: 'Raciocínio Lógico-Matemático', lesson: '5', topic: 'Funções e Gráficos do 1º Grau', type: 'pdf' },
            { date: '2025-09-02', subject: 'Conhecimentos Específicos', lesson: '16', topic: 'Lei nº 13.146/15 - Exercícios', type: 'video' },
            { date: '2025-09-02', subject: 'Conhecimentos Específicos', lesson: '17', topic: 'Lei nº 13.146/15 - Exercícios II', type: 'video' },
            { date: '2025-09-02', subject: 'Conhecimentos Específicos', lesson: '18', topic: 'Lei nº 13.146/15 - Exercícios III', type: 'video' },
            { date: '2025-09-02', subject: 'Conhecimentos Específicos', lesson: '1', topic: 'Teorias e Técnicas Psicoterápicas', type: 'video' },
            { date: '2025-09-02', subject: 'Língua Portuguesa', lesson: '3', topic: 'Mecanismos de Coesão Textual II', type: 'video' },
            { date: '2025-09-02', subject: 'Língua Portuguesa', lesson: '4', topic: 'Coesão Sequencial e Emprego de Conectivos', type: 'video' },
            { date: '2025-09-02', subject: 'Língua Portuguesa', lesson: '5', topic: 'Coesão Sequencial e Emprego de Conectivos II', type: 'video' },
            { date: '2025-09-03', subject: 'Raciocínio Lógico-Matemático', lesson: '5', topic: 'Funções e Gráficos do 1º Grau', type: 'pdf' },
            { date: '2025-09-03', subject: 'Língua Portuguesa', lesson: '5', topic: 'Coesão Sequencial e Emprego de Conectivos II', type: 'video' },
            { date: '2025-09-03', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'Psicoterapia', type: 'video' },
            { date: '2025-09-03', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'Psicoterapia II', type: 'video' },
            { date: '2025-09-03', subject: 'Conhecimentos Específicos', lesson: '1', topic: 'TTP - Psicoterapia Breve - Origens, Linhas, Características Comuns', type: 'video' },
            { date: '2025-09-03', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'TTP - Psicoterapia Breve - PBSP, Conceitos Básicos, EEC, Efeito Carambola', type: 'video' },
            { date: '2025-09-03', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'TTP - Psicoterapia Breve - Caracterísiticas Técnicas, Diferenças', type: 'video' },
            { date: '2025-09-04', subject: 'Raciocínio Lógico-Matemático', lesson: '5', topic: 'Funções e Gráficos do 1º Grau', type: 'pdf' },
            { date: '2025-09-04', subject: 'Administração Pública', lesson: '5', topic: 'Direitos Políticos e Partidos Políticos', type: 'pdf' },
            { date: '2025-09-04', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'TTP - Psicoterapia Breve - Caracterisiticas Técnicas, Diferenças', type: 'video' },
            { date: '2025-09-04', subject: 'Conhecimentos Específicos', lesson: '4', topic: 'TTP - Psicoterapia Breve - Tripé, Alta, Indicações e Contra - Indicações', type: 'video' },
            { date: '2025-09-04', subject: 'Conhecimentos Específicos', lesson: '5', topic: 'TTP - Psicoterapia Breve - Terapia Cognitivo Comportamental - Princípios', type: 'video' },
            { date: '2025-09-04', subject: 'Conhecimentos Específicos', lesson: '6', topic: 'TTP - Psicoterapia Breve - Reestruturação Cognitiva e Terapia de Exposição Prolongada', type: 'video' },
            { date: '2025-09-04', subject: 'Conhecimentos Específicos', lesson: '7', topic: 'TTP - Psicoterapia Breve - Resolução de Questões', type: 'video' },
            { date: '2025-09-04', subject: 'Conhecimentos Específicos', lesson: '8', topic: 'TTP- Psicoterapia Breve - Resolução de Questões II', type: 'video' },
            { date: '2025-09-05', subject: 'Administração Pública', lesson: '5', topic: 'Direitos Políticos e Partidos Políticos', type: 'pdf' },
            { date: '2025-09-05', subject: 'Raciocínio Lógico-Matemático', lesson: '6', topic: 'Funções e Gráficos do 2º Grau', type: 'pdf' },
            { date: '2025-09-05', subject: 'Conhecimentos Específicos', lesson: '1', topic: 'Avaliação Psicológica e Psicodiagnóstico - Entrevista Psicológica e Técnicas de Entrevista - Conceitos Básicos - Entrevista', type: 'video' },
            { date: '2025-09-05', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'Avaliação Psicológica e Psicodiagnóstico - Entrevista Psicológica e Técnicas de Entrevista - Conceitos Básicos - Classificações e Resolução de Questões', type: 'video' },
            { date: '2025-09-05', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'Avaliação Psicológica e Psicodiagnóstico - Entrevista Psicológica e Técnicas de Entrevista - Conceitos Básicos - Técnicas e Resolução de Questões', type: 'video' },
            { date: '2025-09-05', subject: 'Conhecimentos Específicos', lesson: '4', topic: 'Avaliação Psicológica e Psicodiagnóstico - Entrevista Psicológica e Técnicas de Entrevista - Conceitos Básicos - Técnicas e Resolução de Questões II', type: 'video' },
            { date: '2025-09-05', subject: 'Conhecimentos Específicos', lesson: '5', topic: 'Avaliação Psicológica e Psicodiagnóstico - Entrevista Psicológica e Técnicas de Entrevista - Resolução de Questões', type: 'video' },
            { date: '2025-09-05', subject: 'Conhecimentos Específicos', lesson: '1', topic: 'Psicanálise - Fundamentos', type: 'video' },
            { date: '2025-09-06', subject: 'Conhecimentos Específicos', lesson: '1', topic: 'Psicanálise - Fundamentos', type: 'video' },
            { date: '2025-09-06', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'Psicanálise - Fundamentos II', type: 'video' },
            { date: '2025-09-06', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'Psicanálise - Fundamentos III', type: 'video' },
            { date: '2025-09-06', subject: 'Conhecimentos Específicos', lesson: '4', topic: 'Mecanismos de Defesa do Ego', type: 'video' },
            { date: '2025-09-06', subject: 'Conhecimentos Específicos', lesson: '5', topic: 'Psicanálise: Escola Freudiana', type: 'video' },
            { date: '2025-09-06', subject: 'Conhecimentos Específicos', lesson: '6', topic: 'Psicanálise: Escola Kleiniana', type: 'video' },
            { date: '2025-09-07', subject: 'Conhecimentos Específicos', lesson: '6', topic: 'Psicanálise: Escola Kleiniana', type: 'video' },
            { date: '2025-09-07', subject: 'Conhecimentos Específicos', lesson: '7', topic: 'Psicanálise: Escola Winnicotiana', type: 'video' },
            { date: '2025-09-07', subject: 'Conhecimentos Específicos', lesson: '8', topic: 'Revisão e Exercícios - Teoria Cognitiva Comportamental', type: 'video' },
            { date: '2025-09-07', subject: 'Conhecimentos Específicos', lesson: '9', topic: 'Abordagem cognitivo - comportamental', type: 'video' },
            { date: '2025-09-07', subject: 'Conhecimentos Específicos', lesson: '10', topic: 'Abordagem cognitivo - comportamental II', type: 'video' },
            { date: '2025-09-08', subject: 'Raciocínio Lógico-Matemático', lesson: '6', topic: 'Funções e Gráficos do 2º Grau', type: 'pdf' },
            { date: '2025-09-08', subject: 'Administração Pública', lesson: '6', topic: 'Organização Político-Administrativa do Estado', type: 'pdf' },
            { date: '2025-09-08', subject: 'Conhecimentos Específicos', lesson: '10', topic: 'Abordagem cognitivo - comportamental II', type: 'video' },
            { date: '2025-09-08', subject: 'Conhecimentos Específicos', lesson: '11', topic: 'Abordagem Sistêmica - Conceitos Básicos', type: 'video' },
            { date: '2025-09-08', subject: 'Conhecimentos Específicos', lesson: '12', topic: 'Abordagem Sistêmica - Conceitos Fundamentais', type: 'video' },
            { date: '2025-09-08', subject: 'Conhecimentos Específicos', lesson: '13', topic: 'Abordagem Sistêmica - Aplicações', type: 'video' },
            { date: '2025-09-08', subject: 'Conhecimentos Específicos', lesson: '14', topic: 'Abordagem Sistémica - Resolução de Questões', type: 'video' },
            { date: '2025-09-08', subject: 'Conhecimentos Específicos', lesson: '15', topic: 'Abordagem psicodramática', type: 'video' },
            { date: '2025-09-09', subject: 'Administração Pública', lesson: '6', topic: 'Organização Político-Administrativa do Estado', type: 'pdf' },
            { date: '2025-09-09', subject: 'Conhecimentos Específicos', lesson: '15', topic: 'Abordagem psicodramática', type: 'video' },
            { date: '2025-09-09', subject: 'Conhecimentos Específicos', lesson: '16', topic: 'Humanismo: Introdução a Abordagem Centrada na Pessoa', type: 'video' },
            { date: '2025-09-09', subject: 'Conhecimentos Específicos', lesson: '17', topic: 'Humanismo: Introdução a Abordagem Centrada na Pessoa II', type: 'video' },
            { date: '2025-09-09', subject: 'Conhecimentos Específicos', lesson: '18', topic: 'Gestalt Terapia', type: 'video' },
            { date: '2025-09-09', subject: 'Conhecimentos Específicos', lesson: '19', topic: 'Gestalt Terapia II', type: 'video' },
            { date: '2025-09-09', subject: 'Conhecimentos Específicos', lesson: '20', topic: 'Gestalt Terapia III', type: 'video' },
            { date: '2025-09-09', subject: 'Conhecimentos Específicos', lesson: '21', topic: 'Gestalt Terapia IV', type: 'video' },
            { date: '2025-09-10', subject: 'Administração Pública', lesson: '6', topic: 'Organização Político-Administrativa do Estado', type: 'pdf' },
            { date: '2025-09-10', subject: 'Raciocínio Lógico-Matemático', lesson: '7', topic: 'Análise Combinatória', type: 'pdf' },
            { date: '2025-09-10', subject: 'Conhecimentos Específicos', lesson: '21', topic: 'Gestalt Terapia IV', type: 'video' },
            { date: '2025-09-10', subject: 'Conhecimentos Específicos', lesson: '22', topic: 'Gestalt Terapia V', type: 'video' },
            { date: '2025-09-10', subject: 'Conhecimentos Específicos', lesson: '23', topic: 'Gestalt Terapia VI', type: 'video' },
            { date: '2025-09-10', subject: 'Conhecimentos Específicos', lesson: '24', topic: 'Revisão e Exercícios - Teoria Humanista', type: 'video' },
            { date: '2025-09-10', subject: 'Conhecimentos Específicos', lesson: '25', topic: 'Revisão e Exercicios - Teorias e Técnicas Psicoterápicas - Questões', type: 'video' },
            { date: '2025-09-10', subject: 'Conhecimentos Específicos', lesson: '26', topic: 'Revisão e Exercícios - Teoria Comportamental', type: 'video' },
            { date: '2025-09-11', subject: 'Raciocínio Lógico-Matemático', lesson: '7', topic: 'Análise Combinatória', type: 'pdf' },
            { date: '2025-09-11', subject: 'Administração Pública', lesson: '7', topic: 'Repartição de Competências', type: 'pdf' },
            { date: '2025-09-11', subject: 'Conhecimentos Específicos', lesson: '26', topic: 'Revisão e Exercícios - Teoria Comportamental', type: 'video' },
            { date: '2025-09-11', subject: 'Conhecimentos Específicos', lesson: '27', topic: 'Abordagem corporal', type: 'video' },
            { date: '2025-09-11', subject: 'Conhecimentos Específicos', lesson: '1', topic: 'Psicopatologia: Noções de psicopatologia geral', type: 'video' },
            { date: '2025-09-11', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'Psicopatologia: Noções de psicopatologia geral II', type: 'video' },
            { date: '2025-09-11', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'Psicopatologia: Noções de psicopatologia geral III', type: 'video' },
            { date: '2025-09-11', subject: 'Conhecimentos Específicos', lesson: '4', topic: 'Psicopatologia: Noções de psicopatologia geral IV', type: 'video' },
            { date: '2025-09-12', subject: 'Administração Pública', lesson: '7', topic: 'Repartição de Competências', type: 'pdf' },
            { date: '2025-09-12', subject: 'Raciocínio Lógico-Matemático', lesson: '8', topic: 'Probabilidades', type: 'pdf' },
            { date: '2025-09-12', subject: 'Conhecimentos Específicos', lesson: '4', topic: 'Psicopatologia: Noções de psicopatologia geral IV', type: 'video' },
            { date: '2025-09-12', subject: 'Conhecimentos Específicos', lesson: '5', topic: 'Psicopatologia - Transtorno do Jogo Eletrônico ou Pela Internet', type: 'video' },
            { date: '2025-09-12', subject: 'Conhecimentos Específicos', lesson: '6', topic: 'Psicopatologia - Tratamento da Dependência de Internet e Jogos Eletrônicos', type: 'video' },
            { date: '2025-09-12', subject: 'Conhecimentos Específicos', lesson: '7', topic: 'Psicopatologia - Transtornos Alimentares', type: 'video' },
            { date: '2025-09-12', subject: 'Conhecimentos Específicos', lesson: '8', topic: 'Psicopatologia - Transtornos Depressivos', type: 'video' },
            { date: '2025-09-12', subject: 'Conhecimentos Específicos', lesson: '9', topic: 'Psicopatologia - Transtornos Depressivos II', type: 'video' },
            { date: '2025-09-13', subject: 'Conhecimentos Específicos', lesson: '9', topic: 'Psicopatologia - Transtornos Depressivos II', type: 'video' },
            { date: '2025-09-13', subject: 'Conhecimentos Específicos', lesson: '10', topic: 'Psicopatologia - Transtornos Depressivos - Resolução de Questões', type: 'video' },
            { date: '2025-09-13', subject: 'Conhecimentos Específicos', lesson: '11', topic: 'Psicopatologia - Transtornos da Personalidade', type: 'video' },
            { date: '2025-09-13', subject: 'Conhecimentos Específicos', lesson: '12', topic: 'Psicopatologia - Transtornos da Personalidade II', type: 'video' },
            { date: '2025-09-13', subject: 'Conhecimentos Específicos', lesson: '13', topic: 'Psicopatologia - Transtornos da Personalidade III', type: 'video' },
            { date: '2025-09-13', subject: 'Conhecimentos Específicos', lesson: '14', topic: 'Psicopatologia - Espectro da Esquizofrenia e outros Transtornos Psicóticos', type: 'video' },
            { date: '2025-09-14', subject: 'Conhecimentos Específicos', lesson: '14', topic: 'Psicopatologia - Espectro da Esquizofrenia e outros Transtornos Psicóticos', type: 'video' },
            { date: '2025-09-14', subject: 'Conhecimentos Específicos', lesson: '15', topic: 'Psicopatologia - Espectro da Esquizofrenia e outros Transtornos Psicóticos II', type: 'video' },
            { date: '2025-09-14', subject: 'Conhecimentos Específicos', lesson: '16', topic: 'Psicopatologia - Espectro da Esquizofrenia e outros Transtornos Psicóticos - Questões', type: 'video' },
            { date: '2025-09-14', subject: 'Conhecimentos Específicos', lesson: '17', topic: 'Psicopatologia - Transtorno Bipolar e Transtornos Relacionados', type: 'video' },
            { date: '2025-09-14', subject: 'Conhecimentos Específicos', lesson: '18', topic: 'Psicopatologia - Transtorno Bipolar e Transtornos Relacionados II', type: 'video' },
            { date: '2025-09-14', subject: 'Conhecimentos Específicos', lesson: '19', topic: 'Psicopatologia - Transtornos do Neurodesenvolvimento', type: 'video' },
            { date: '2025-09-15', subject: 'Raciocínio Lógico-Matemático', lesson: '8', topic: 'Probabilidades', type: 'pdf' },
            { date: '2025-09-15', subject: 'Conhecimentos Específicos', lesson: '19', topic: 'Psicopatologia - Transtornos do Neurodesenvolvimento', type: 'video' },
            { date: '2025-09-15', subject: 'Conhecimentos Específicos', lesson: '20', topic: 'Psicopatologia - Transtornos Psicológicos', type: 'video' },
            { date: '2025-09-15', subject: 'Conhecimentos Específicos', lesson: '21', topic: 'Psicopatologia - Transtornos do Neurodesenvolvimento e Psicológicos - Exercícios', type: 'video' },
            { date: '2025-09-15', subject: 'Conhecimentos Específicos', lesson: '22', topic: 'Transtorno de Estresse Pós - Traumático', type: 'video' },
            { date: '2025-09-15', subject: 'Conhecimentos Específicos', lesson: '1', topic: 'Resolução CFP 31/2022 1', type: 'video' },
            { date: '2025-09-16', subject: 'Raciocínio Lógico-Matemático', lesson: '8', topic: 'Probabilidades', type: 'pdf' },
            { date: '2025-09-16', subject: 'Administração Pública', lesson: '8', topic: 'Administração Pública', type: 'pdf' },
            { date: '2025-09-16', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'Resolução CFP 31/2022 II', type: 'video' },
            { date: '2025-09-16', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'Resolução CFP 31/2022 III', type: 'video' },
            { date: '2025-09-16', subject: 'Conhecimentos Específicos', lesson: '4', topic: 'Resolução CFP 31/2022 IV', type: 'video' },
            { date: '2025-09-16', subject: 'Conhecimentos Específicos', lesson: '5', topic: 'Avaliação Psicológica e Psicodiagnóstico - Definição de Avaliação Psicológica', type: 'video' },
            { date: '2025-09-16', subject: 'Conhecimentos Específicos', lesson: '6', topic: 'Avaliação Psicológica e Psicodiagnóstico - Tipos de Avaliação', type: 'video' },
            { date: '2025-09-16', subject: 'Conhecimentos Específicos', lesson: '7', topic: 'Avaliação Psicológica e Psicodiagnóstico - Documentos Que Fundamentam a Realização da Avaliação Psicológica & Cartilha', type: 'video' },
            { date: '2025-09-17', subject: 'Administração Pública', lesson: '8', topic: 'Administração Pública', type: 'pdf' },
            { date: '2025-09-17', subject: 'Raciocínio Lógico-Matemático', lesson: '9', topic: 'Progressões Aritméticas e Geométricas', type: 'pdf' },
            { date: '2025-09-17', subject: 'Conhecimentos Específicos', lesson: '7', topic: 'Avaliação Psicológica e Psicodiagnóstico - Documentos Que Fundamentam a Realização da Avaliação Psicológica & Cartilha', type: 'video' },
            { date: '2025-09-17', subject: 'Conhecimentos Específicos', lesson: '8', topic: 'Avaliação Psicológica e Psicodiagnóstico - Documentos Resultantes, Testagem, Satepsi', type: 'video' },
            { date: '2025-09-17', subject: 'Conhecimentos Específicos', lesson: '9', topic: 'Avaliação Psicológica e Psicodiagnóstico - Psicodiagnóstico', type: 'video' },
            { date: '2025-09-17', subject: 'Conhecimentos Específicos', lesson: '10', topic: 'Avaliação Psicológica e Psicodiagnóstico - Resolução de Questões', type: 'video' },
            { date: '2025-09-17', subject: 'Conhecimentos Específicos', lesson: '11', topic: 'Avaliação Psicológica e Psicodiagnóstico - Resolução de Questões II', type: 'video' },
            { date: '2025-09-17', subject: 'Conhecimentos Específicos', lesson: '12', topic: 'Avaliação Psicológica e Psicodiagnóstico - Resolução de Questões III', type: 'video' },
            { date: '2025-09-17', subject: 'Conhecimentos Específicos', lesson: '13', topic: 'Fundamentos e Etapas da Avaliação Psicológica', type: 'video' },
            { date: '2025-09-18', subject: 'Raciocínio Lógico-Matemático', lesson: '9', topic: 'Progressões Aritméticas e Geométricas', type: 'pdf' },
            { date: '2025-09-18', subject: 'Administração Pública', lesson: '1', topic: 'Organização Administrativa', type: 'pdf' },
            { date: '2025-09-18', subject: 'Conhecimentos Específicos', lesson: '13', topic: 'Fundamentos e Etapas da Avaliação Psicológica', type: 'video' },
            { date: '2025-09-18', subject: 'Conhecimentos Específicos', lesson: '14', topic: 'Avaliação Psicológica e Psicodiagnóstico - Instrumentos de Avaliação Psicológica - Conceitos Básicos', type: 'video' },
            { date: '2025-09-18', subject: 'Conhecimentos Específicos', lesson: '15', topic: 'Avaliação Psicológica e Psicodiagnóstico - Instrumentos de Avaliação Psicológica - Conceitos Básicos II', type: 'video' },
            { date: '2025-09-18', subject: 'Conhecimentos Específicos', lesson: '16', topic: 'Avaliação Psicológica e Psicodiagnóstico - Instrumentos de Avaliação Psicológica - Resolução de Questões', type: 'video' },
            { date: '2025-09-18', subject: 'Conhecimentos Específicos', lesson: '17', topic: 'Avaliação Psicológica e Psicodiagnóstico - Instrumentos de Avaliação Psicológica - Resolução de Questões II', type: 'video' },
            { date: '2025-09-18', subject: 'Conhecimentos Específicos', lesson: '18', topic: 'Avaliação Psicológica e Psicodiagnóstico - Instrumentos de Avaliação Psicológica - Resolução de Questões III', type: 'video' },
            { date: '2025-09-19', subject: 'Administração Pública', lesson: '1', topic: 'Organização Administrativa', type: 'pdf' },
            { date: '2025-09-19', subject: 'Conhecimentos Específicos', lesson: '18', topic: 'Avaliação Psicológica e Psicodiagnóstico - Instrumentos de Avaliação Psicológica - Resolução de Questões II', type: 'video' },
            { date: '2025-09-19', subject: 'Conhecimentos Específicos', lesson: '19', topic: 'Critérios de Seleção, Avaliação e Interpretação dos Resultados - Conceitos Básicos e Resolução de Questões', type: 'video' },
            { date: '2025-09-19', subject: 'Conhecimentos Específicos', lesson: '20', topic: 'Critérios de Seleção, Avaliação e Interpretação dos Resultados - Resolução de Questões', type: 'video' },
            { date: '2025-09-19', subject: 'Conhecimentos Específicos', lesson: '21', topic: 'Testagem Psicológica - Testes Psicométricos e Impressionista', type: 'video' },
            { date: '2025-09-19', subject: 'Conhecimentos Específicos', lesson: '22', topic: 'Testagem Psicológica - Testes de Inteligência', type: 'video' },
            { date: '2025-09-19', subject: 'Conhecimentos Específicos', lesson: '23', topic: 'Testagem Psicológica - Testes de Inteligência e de Personalidade', type: 'video' },
            { date: '2025-09-19', subject: 'Conhecimentos Específicos', lesson: '24', topic: 'Testagem Psicológica - Outros Testes, Inventários', type: 'video' },
            { date: '2025-09-20', subject: 'Conhecimentos Específicos', lesson: '24', topic: 'Testagem Psicológica - Outros Testes, Inventários', type: 'video' },
            { date: '2025-09-20', subject: 'Conhecimentos Específicos', lesson: '25', topic: 'Testagem Psicológica - Técnicas Projetivas, Técnicas Gráficas e Testes Motores', type: 'video' },
            { date: '2025-09-20', subject: 'Conhecimentos Específicos', lesson: '26', topic: 'Testagem Psicológica - Resolução de Questões', type: 'video' },
            { date: '2025-09-20', subject: 'Conhecimentos Específicos', lesson: '1', topic: 'Lei Federal n. 10.216/2001', type: 'video' },
            { date: '2025-09-20', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'Portaria nº 336/2002', type: 'video' },
            { date: '2025-09-20', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'Portaria nº 336/2002 II', type: 'video' },
            { date: '2025-09-21', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'Portaria nº 336/2002 II', type: 'video' },
            { date: '2025-09-21', subject: 'Conhecimentos Específicos', lesson: '4', topic: 'Portaria nº 336/2002 III', type: 'video' },
            { date: '2025-09-21', subject: 'Conhecimentos Específicos', lesson: '5', topic: 'Portaria nº 336/2002 IV', type: 'video' },
            { date: '2025-09-21', subject: 'Conhecimentos Específicos', lesson: '6', topic: 'Apoio Matricial - Definição', type: 'video' },
            { date: '2025-09-21', subject: 'Conhecimentos Específicos', lesson: '7', topic: 'Apoio Matricial - Ações de Matriciamento', type: 'video' },
            { date: '2025-09-21', subject: 'Conhecimentos Específicos', lesson: '8', topic: 'Apoio Matricial - Resolução de questões', type: 'video' },
            { date: '2025-09-22', subject: 'Administração Pública', lesson: '1', topic: 'Organização Administrativa', type: 'pdf' },
            { date: '2025-09-22', subject: 'Raciocínio Lógico-Matemático', lesson: '10', topic: 'Números Inteiros', type: 'pdf' },
            { date: '2025-09-22', subject: 'Conhecimentos Específicos', lesson: '8', topic: 'Apoio Matricial - Resolução de questões', type: 'video' },
            { date: '2025-09-22', subject: 'Conhecimentos Específicos', lesson: '9', topic: 'Projeto Terapêutico Singular', type: 'video' },
            { date: '2025-09-22', subject: 'Conhecimentos Específicos', lesson: '10', topic: 'Projeto Terapêutico Singular - Resolução de Questões', type: 'video' },
            { date: '2025-09-22', subject: 'Conhecimentos Específicos', lesson: '11', topic: 'Prevenção Primária (Universal, Seletiva e Indicada), Secundária e Terciária em Saúde Mental - Prevenção Primária e Níveis de Risco', type: 'video' },
            { date: '2025-09-22', subject: 'Conhecimentos Específicos', lesson: '12', topic: 'Prevenção Primária (Universal, Seletiva e Indicada), Secundária e Terciária em Saúde Mental - Prevenção Secundária e Terciária e Modelo Integrativo', type: 'video' },
            { date: '2025-09-23', subject: 'Raciocínio Lógico-Matemático', lesson: '10', topic: 'Números Inteiros', type: 'pdf' },
            { date: '2025-09-23', subject: 'Administração Pública', lesson: '2', topic: 'Lei n. 8.429/1992 - Lei de Improbidade Administrativa', type: 'pdf' },
            { date: '2025-09-23', subject: 'Conhecimentos Específicos', lesson: '12', topic: 'Prevenção Primária (Universal, Seletiva e Indicada), Secundária e Terciária em Saúde Mental - Prevenção Secundária e Terciária e Modelo Integrativo', type: 'video' },
            { date: '2025-09-23', subject: 'Conhecimentos Específicos', lesson: '13', topic: 'Prevenção Primária (Universal, Seletiva e Indicada), Secundária e Terciária em Saúde Mental - Resolução de Questões', type: 'video' },
            { date: '2025-09-23', subject: 'Conhecimentos Específicos', lesson: '14', topic: 'Rede de Antenção Psicossocial - Pontos de Atenção', type: 'video' },
            { date: '2025-09-23', subject: 'Conhecimentos Específicos', lesson: '15', topic: 'Rede de Antenção Psicossocial - Pontos de Atenção II', type: 'video' },
            { date: '2025-09-23', subject: 'Conhecimentos Específicos', lesson: '16', topic: 'Rede de Antenção Psicossocial - Resolução de Questões', type: 'video' },
            { date: '2025-09-23', subject: 'Conhecimentos Específicos', lesson: '17', topic: 'Rede de Antenção Psicossocial - Resolução de Questões II', type: 'video' },
            { date: '2025-09-24', subject: 'Administração Pública', lesson: '2', topic: 'Lei n. 8.429/1992 - Lei de Improbidade Administrativa', type: 'pdf' },
            { date: '2025-09-24', subject: 'Raciocínio Lógico-Matemático', lesson: '11', topic: 'Números Racionais e Reais', type: 'pdf' },
            { date: '2025-09-24', subject: 'Conhecimentos Específicos', lesson: '17', topic: 'Rede de Antenção Psicossocial - Resolução de Questões II', type: 'video' },
            { date: '2025-09-24', subject: 'Conhecimentos Específicos', lesson: '1', topic: 'Atuação em Equipe Multiprofissional', type: 'video' },
            { date: '2025-09-24', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'Atuação em Equipe Multiprofissional II', type: 'video' },
            { date: '2025-09-24', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'Atuação em Equipe Multiprofissional III', type: 'video' },
            { date: '2025-09-24', subject: 'Conhecimentos Específicos', lesson: '4', topic: 'Atuação Em Equipe Multiprofissional - Resolução de Questões', type: 'video' },
            { date: '2025-09-24', subject: 'Conhecimentos Específicos', lesson: '5', topic: 'Atuação Em Equipe Multiprofissional - Resolução de Questões II', type: 'video' },
            { date: '2025-09-25', subject: 'Raciocínio Lógico-Matemático', lesson: '11', topic: 'Números Racionais e Reais', type: 'pdf' },
            { date: '2025-09-25', subject: 'Administração Pública', lesson: '3', topic: 'Lei n. 14.133/2021-Licitação - Comentada, Comparada e Esquematizada', type: 'pdf' },
            { date: '2025-09-25', subject: 'Conhecimentos Específicos', lesson: '5', topic: 'Atuação Em Equipe Multiprofissional - Resolução de Questões II', type: 'video' },
            { date: '2025-09-25', subject: 'Conhecimentos Específicos', lesson: '6', topic: 'Atuação Em Equipe Multiprofissional - Resolução de Questões III', type: 'video' },
            { date: '2025-09-25', subject: 'Conhecimentos Específicos', lesson: '1', topic: 'Atuação dos Psicólogos junto às Políticas Públicas e em Programas Sociais', type: 'video' },
            { date: '2025-09-25', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'Atuação dos Psicólogos junto às Políticas Públicas e em Programas Sociais II', type: 'video' },
            { date: '2025-09-25', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'Atuação dos Psicólogos junto às Políticas Públicas e em Programas Sociais III', type: 'video' },
            { date: '2025-09-26', subject: 'Administração Pública', lesson: '3', topic: 'Lei n. 14.133/2021-Licitação - Comentada, Comparada e Esquematizada', type: 'pdf' },
            { date: '2025-09-26', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'Atuação dos Psicólogos junto às Políticas Públicas e em Programas Sociais III', type: 'video' },
            { date: '2025-09-26', subject: 'Conhecimentos Específicos', lesson: '1', topic: 'A Família e suas Diferentes Configurações - História e Função Social da Família', type: 'video' },
            { date: '2025-09-26', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'A Familia e suas Diferentes Configurações - Configurações, Estruturas e Sistemas Familiares', type: 'video' },
            { date: '2025-09-26', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'A Família e suas Diferentes Configurações - Papéis, Regras, Fronteiras e Saúde Familiar', type: 'video' },
            { date: '2025-09-26', subject: 'Conhecimentos Específicos', lesson: '4', topic: 'A Família e suas Diferentes Configurações - Resolução de Questões', type: 'video' },
            { date: '2025-09-27', subject: 'Conhecimentos Específicos', lesson: '4', topic: 'A Família e suas Diferentes Configurações - Resolução de Questões', type: 'video' },
            { date: '2025-09-27', subject: 'Conhecimentos Específicos', lesson: '1', topic: 'Grupos em vulnerabilidade social. Atendimento e intervenções psicossociais', type: 'video' },
            { date: '2025-09-27', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'Grupos em vulnerabilidade social. Atendimento e intervenções psicossociais II', type: 'video' },
            { date: '2025-09-27', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'Grupos em vulnerabilidade social. Atendimento e intervenções psicossociais III', type: 'video' },
            { date: '2025-09-27', subject: 'Conhecimentos Específicos', lesson: '1', topic: 'Aspectos Psicossociais do Fenômeno da Violência - Contextualizando a Violência', type: 'video' },
            { date: '2025-09-28', subject: 'Conhecimentos Específicos', lesson: '1', topic: 'Aspectos Psicossociais do Fenômeno da Violência Contextualizando a Violência', type: 'video' },
            { date: '2025-09-28', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'Aspectos Psicossociais do Fenômeno da Violência - Tipos de Violência', type: 'video' },
            { date: '2025-09-28', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'Aspectos Psicossociais do Fenômeno da Violência - Resolução de Questões', type: 'video' },
            { date: '2025-09-28', subject: 'Conhecimentos Específicos', lesson: '4', topic: 'Assédio moral, assédio organizacional e assédio sexual', type: 'video' },
            { date: '2025-09-28', subject: 'Conhecimentos Específicos', lesson: '5', topic: 'Assédio moral, assédio organizacional e assédio sexual II', type: 'video' },
            { date: '2025-09-29', subject: 'Administração Pública', lesson: '3', topic: 'Lei n. 14.133/2021-Licitação - Comentada, Comparada e Esquematizada', type: 'pdf' },
            { date: '2025-09-29', subject: 'Conhecimentos Específicos', lesson: '5', topic: 'Assédio moral, assédio organizacional e assédio sexual II', type: 'video' },
            { date: '2025-09-29', subject: 'Conhecimentos Específicos', lesson: '6', topic: 'Assédio moral, assédio organizacional e assédio sexual III', type: 'video' },
            { date: '2025-09-29', subject: 'Conhecimentos Específicos', lesson: '7', topic: 'Assédio moral, assédio organizacional e assédio sexual IV', type: 'video' },
            { date: '2025-09-29', subject: 'Conhecimentos Específicos', lesson: '8', topic: 'Assédio moral, assédio organizacional e assédio sexual V', type: 'video' },
            { date: '2025-09-29', subject: 'Conhecimentos Específicos', lesson: '9', topic: 'Assédio moral, assédio organizacional e assédio sexual VI', type: 'video' },
            { date: '2025-09-29', subject: 'Conhecimentos Específicos', lesson: '1', topic: 'O Papel da Agressividade no Desenvolvimento Humano - Teorias da Agressividade', type: 'video' },
            { date: '2025-09-30', subject: 'Administração Pública', lesson: '3', topic: 'Lei n. 14.133/2021 - Licitação - Comentada, Comparada e Esquematizada', type: 'pdf' },
            { date: '2025-09-30', subject: 'Raciocínio Lógico-Matemático', lesson: '12', topic: 'Geometria Plana: Áreas', type: 'pdf' },
            { date: '2025-09-30', subject: 'Conhecimentos Específicos', lesson: '1', topic: 'O Papel da Agressividade no Desenvolvimento Humano - Teorias da Agressividade', type: 'video' },
            { date: '2025-09-30', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'O Papel da Agressividade no Desenvolvimento Humano - Winnicott e a Agressividade', type: 'video' },
            { date: '2025-09-30', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'O Papel da Agressividade no Desenvolvimento Humano - Resolução de Questões', type: 'video' },
            { date: '2025-09-30', subject: 'Conhecimentos Específicos', lesson: '1', topic: 'Educação Inclusiva', type: 'video' },
            { date: '2025-09-30', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'Educação Inclusiva II', type: 'video' },
            { date: '2025-09-30', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'Educação Inclusiva III', type: 'video' },
            // --- OUTUBRO 2025 ---
            { date: '2025-10-01', subject: 'Raciocínio Lógico-Matemático', lesson: '12', topic: 'Geometria Plana: Áreas', type: 'pdf' },
            { date: '2025-10-01', subject: 'Administração Pública', lesson: '4', topic: 'Lei n. 12.527/2011-Acesso à Informação', type: 'pdf' },
            { date: '2025-10-01', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'Educação Inclusiva III', type: 'video' },
            { date: '2025-10-01', subject: 'Conhecimentos Específicos', lesson: '4', topic: 'Educação Inclusiva IV', type: 'video' },
            { date: '2025-10-01', subject: 'Conhecimentos Específicos', lesson: '1', topic: 'Psicologia do Desenvolvimento - René Spitz', type: 'video' },
            { date: '2025-10-01', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'Psicologia do Desenvolvimento - Alexander Luria - Desenvolvimento Cognitivo', type: 'video' },
            { date: '2025-10-01', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'Teóricos do desenvolvimento: Piaget', type: 'video' },
            { date: '2025-10-02', subject: 'Administração Pública', lesson: '4', topic: 'Lei n. 12.527/2011 - Acesso à Informação', type: 'pdf' },
            { date: '2025-10-02', subject: 'Raciocínio Lógico-Matemático', lesson: '13', topic: 'Geometria Plana: Segmentos', type: 'pdf' },
            { date: '2025-10-02', subject: 'Conhecimentos Específicos', lesson: '4', topic: 'Teóricos do desenvolvimento: Vigotski', type: 'video' },
            { date: '2025-10-02', subject: 'Conhecimentos Específicos', lesson: '5', topic: 'Teóricos do desenvolvimento - Jerome Bruner - Introdução', type: 'video' },
            { date: '2025-10-02', subject: 'Conhecimentos Específicos', lesson: '6', topic: 'Teóricos do desenvolvimento - Jerome Bruner - Introdução II', type: 'video' },
            { date: '2025-10-02', subject: 'Conhecimentos Específicos', lesson: '1', topic: 'Processo de comunicação na organização', type: 'video' },
            { date: '2025-10-02', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'Processo de comunicação na organização II', type: 'video' },
            { date: '2025-10-03', subject: 'Raciocínio Lógico-Matemático', lesson: '13', topic: 'Geometria Plana: Segmentos', type: 'pdf' },
            { date: '2025-10-03', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'Processo de comunicação na organização II', type: 'video' },
            { date: '2025-10-03', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'Psicologia de Grupo e Equipes de Trabalho - Definindo Grupo e Equipe', type: 'video' },
            { date: '2025-10-03', subject: 'Conhecimentos Específicos', lesson: '4', topic: 'Psicologia de Grupo e Equipes de Trabalho - Estrutura dos Grupos', type: 'video' },
            { date: '2025-10-03', subject: 'Conhecimentos Específicos', lesson: '5', topic: 'Psicologia de Grupo e Equipes de Trabalho Estágios de Desenvolvimento do Grupo', type: 'video' },
            { date: '2025-10-03', subject: 'Conhecimentos Específicos', lesson: '6', topic: 'Psicologia de Grupo e Equipes de Trabalho - Equipes de Trabalho', type: 'video' },
            { date: '2025-10-04', subject: 'Conhecimentos Específicos', lesson: '6', topic: 'Psicologia de Grupo e Equipes de Trabalho - Equipes de Trabalho', type: 'video' },
            { date: '2025-10-04', subject: 'Conhecimentos Específicos', lesson: '7', topic: 'Psicologia de Grupo e Equipes de Trabalho - Componentes Básicos das Equipes Eficazes', type: 'video' },
            { date: '2025-10-04', subject: 'Conhecimentos Específicos', lesson: '8', topic: 'Psicologia de Grupo e Equipes de Trabalho - Componentes Básicos das Equipes Eficazes II', type: 'video' },
            { date: '2025-10-04', subject: 'Conhecimentos Específicos', lesson: '9', topic: 'Processos de Grupos - Fundamentos', type: 'video' },
            { date: '2025-10-04', subject: 'Conhecimentos Específicos', lesson: '10', topic: 'Estrutura de Grupo - Coesão e Conflito', type: 'video' },
            { date: '2025-10-05', subject: 'Conhecimentos Específicos', lesson: '10', topic: 'Estrutura de Grupo - Coesão e Conflito', type: 'video' },
            { date: '2025-10-05', subject: 'Conhecimentos Específicos', lesson: '11', topic: 'Processos de Grupo Conflito e Tomada de Decisão', type: 'video' },
            { date: '2025-10-05', subject: 'Conhecimentos Específicos', lesson: '12', topic: 'Processos de Grupo - Questões', type: 'video' },
            { date: '2025-10-05', subject: 'Conhecimentos Específicos', lesson: '13', topic: 'Liderança I', type: 'video' },
            { date: '2025-10-05', subject: 'Conhecimentos Específicos', lesson: '14', topic: 'Liderança II', type: 'video' },
            { date: '2025-10-05', subject: 'Conhecimentos Específicos', lesson: '15', topic: 'Liderança III', type: 'video' },
            { date: '2025-10-06', subject: 'Raciocínio Lógico-Matemático', lesson: '13', topic: 'Geometria Plana: Segmentos', type: 'pdf' },
            { date: '2025-10-06', subject: 'Administração Pública', lesson: '5', topic: 'Lei n. 13.709/2018-Lei Geral de Proteção de Dados - Parte I', type: 'pdf' },
            { date: '2025-10-06', subject: 'Conhecimentos Específicos', lesson: '15', topic: 'Liderança III', type: 'video' },
            { date: '2025-10-06', subject: 'Conhecimentos Específicos', lesson: '16', topic: 'Liderança IV', type: 'video' },
            { date: '2025-10-06', subject: 'Conhecimentos Específicos', lesson: '17', topic: 'Cultura e Clima Organizacional: paradigmas, conceitos, elementos e dinâmica. Evolução conceitual, componentes e estratégias de gestão', type: 'video' },
            { date: '2025-10-06', subject: 'Conhecimentos Específicos', lesson: '18', topic: 'Cultura e Clima Organizacional: paradigmas, conceitos, elementos e dinâmica. Evolução conceitual, componentes e estratégias de gestão II', type: 'video' },
            { date: '2025-10-06', subject: 'Conhecimentos Específicos', lesson: '19', topic: 'Cultura e Clima Organizacional: paradigmas, conceitos, elementos e dinâmica. Evolução conceitual, componentes e estratégias de gestão III', type: 'video' },
            { date: '2025-10-06', subject: 'Conhecimentos Específicos', lesson: '20', topic: 'Gerenciamento da pluralidade nas empresas', type: 'video' },
            { date: '2025-10-07', subject: 'Administração Pública', lesson: '5', topic: 'Lei n. 13.709/2018-Lei Geral de Proteção de Dados - Parte I', type: 'pdf' },
            { date: '2025-10-07', subject: 'Raciocínio Lógico-Matemático', lesson: '14', topic: 'Trigonometria', type: 'pdf' },
            { date: '2025-10-07', subject: 'Conhecimentos Específicos', lesson: '20', topic: 'Gerenciamento da pluralidade nas empresas', type: 'video' },
            { date: '2025-10-07', subject: 'Conhecimentos Específicos', lesson: '21', topic: 'Visão Geral da Psicopatologia', type: 'video' },
            { date: '2025-10-07', subject: 'Conhecimentos Específicos', lesson: '22', topic: 'Psicopatologia: Fundamentos', type: 'video' },
            { date: '2025-10-07', subject: 'Conhecimentos Específicos', lesson: '23', topic: 'Psicopatologia: Fundamentos II', type: 'video' },
            { date: '2025-10-07', subject: 'Conhecimentos Específicos', lesson: '24', topic: 'Psicopatologia: Fundamentos III', type: 'video' },
            { date: '2025-10-08', subject: 'Raciocínio Lógico-Matemático', lesson: '14', topic: 'Trigonometria', type: 'pdf' },
            { date: '2025-10-08', subject: 'Administração Pública', lesson: '6', topic: 'Lei n. 13.709/2018- Lei Geral de Proteção de Dados - Parte II', type: 'pdf' },
            { date: '2025-10-08', subject: 'Conhecimentos Específicos', lesson: '24', topic: 'Psicopatologia: Fundamentos III', type: 'video' },
            { date: '2025-10-08', subject: 'Conhecimentos Específicos', lesson: '25', topic: 'Saúde Mental no Contexto Laboral - Psicopatologia do Trabalho', type: 'video' },
            { date: '2025-10-08', subject: 'Conhecimentos Específicos', lesson: '26', topic: 'Psicodinâmica do Trabalho - Fundamentos', type: 'video' },
            { date: '2025-10-08', subject: 'Conhecimentos Específicos', lesson: '27', topic: 'Psicodinâmica do Trabalho - A Clínica do Trabalho', type: 'video' },
            { date: '2025-10-09', subject: 'Administração Pública', lesson: '6', topic: 'Lei n. 13.709/2018 Lei Geral de Proteção de Dados - Parte II', type: 'pdf' },
            { date: '2025-10-09', subject: 'Raciocínio Lógico-Matemático', lesson: '15', topic: 'Números Complexos e Polinômios', type: 'pdf' },
            { date: '2025-10-09', subject: 'Conhecimentos Específicos', lesson: '27', topic: 'Psicodinâmica do Trabalho - A Clínica do Trabalho', type: 'video' },
            { date: '2025-10-09', subject: 'Conhecimentos Específicos', lesson: '28', topic: 'Psicodinâmica do Trabalho - Adoecimentos Psiquicos Prevalentes no Contexto de Trabalho', type: 'video' },
            { date: '2025-10-09', subject: 'Conhecimentos Específicos', lesson: '29', topic: 'Psicossociologia do Trabalho', type: 'video' },
            { date: '2025-10-09', subject: 'Conhecimentos Específicos', lesson: '30', topic: 'Ergonomia da Atividade e Psicopatologia do Trabalho', type: 'video' },
            { date: '2025-10-09', subject: 'Conhecimentos Específicos', lesson: '31', topic: 'Ergonomia da Atividade e Psicopatologia do Trabalho II', type: 'video' },
            { date: '2025-10-10', subject: 'Raciocínio Lógico-Matemático', lesson: '15', topic: 'Números Complexos e Polinômios', type: 'pdf' },
            { date: '2025-10-10', subject: 'Administração Pública', lesson: '7', topic: 'Lei 13.709/2018 - Lei Geral de Proteção de Dados - Parte III', type: 'pdf' },
            { date: '2025-10-10', subject: 'Conhecimentos Específicos', lesson: '31', topic: 'Ergonomia da Atividade e Psicopatologia do Trabalho II', type: 'video' },
            { date: '2025-10-10', subject: 'Conhecimentos Específicos', lesson: '32', topic: 'Ergonomia da Atividade e Psicopatologia do Trabalho III', type: 'video' },
            { date: '2025-10-10', subject: 'Conhecimentos Específicos', lesson: '33', topic: 'Relação entre trabalho, processos de subjetivação e processos de saúde e adoecimento relacionado ao trabalho', type: 'video' },
            { date: '2025-10-10', subject: 'Conhecimentos Específicos', lesson: '34', topic: 'Saúde Mental no Contexto Laboral - Psicodinâmica do Trabalho', type: 'video' },
            { date: '2025-10-10', subject: 'Conhecimentos Específicos', lesson: '35', topic: 'Adoecimentos Psíquicos Prevalentes no Trabalho', type: 'video' },
            { date: '2025-10-11', subject: 'Conhecimentos Específicos', lesson: '35', topic: 'Adoecimentos Psíquicos Prevalentes no Trabalho', type: 'video' },
            { date: '2025-10-11', subject: 'Conhecimentos Específicos', lesson: '36', topic: 'Adoecimentos Psíquicos Prevalentes no Trabalho II', type: 'video' },
            { date: '2025-10-11', subject: 'Conhecimentos Específicos', lesson: '37', topic: 'Gestão por competências: Conceitos e principais abordagens metodológicas. Gestão por Competências no Serviço Público', type: 'video' },
            { date: '2025-10-11', subject: 'Conhecimentos Específicos', lesson: '38', topic: 'Gestão por competências: Conceitos e principais abordagens metodológicas. Gestão por Competências no Serviço Público II', type: 'video' },
            { date: '2025-10-11', subject: 'Conhecimentos Específicos', lesson: '39', topic: 'Gestão por competências: Conceitos e principais abordagens metodológicas. Gestão por Competências no Serviço Público III', type: 'video' },
            { date: '2025-10-11', subject: 'Conhecimentos Específicos', lesson: '40', topic: 'Gestão por competências: Conceitos e principais abordagens metodológicas. Gestão por Competências no Serviço Público IV', type: 'video' },
            { date: '2025-10-12', subject: 'Conhecimentos Específicos', lesson: '40', topic: 'Gestão por competências: Conceitos e principais abordagens metodológicas. Gestão por Competências no Serviço Público IV', type: 'video' },
            { date: '2025-10-12', subject: 'Conhecimentos Específicos', lesson: '41', topic: 'Avaliação de desempenho e performance', type: 'video' },
            { date: '2025-10-12', subject: 'Conhecimentos Específicos', lesson: '42', topic: 'Avaliação de desempenho e performance II', type: 'video' },
            { date: '2025-10-12', subject: 'Conhecimentos Específicos', lesson: '43', topic: 'Avaliação de desempenho e performance III', type: 'video' },
            { date: '2025-10-12', subject: 'Conhecimentos Específicos', lesson: '44', topic: 'Educação Corporativa TD&E e Planejamento', type: 'video' },
            { date: '2025-10-12', subject: 'Conhecimentos Específicos', lesson: '45', topic: 'Educação Corporativa TD&E e Planejamento', type: 'video' },
            { date: '2025-10-13', subject: 'Administração Pública', lesson: '7', topic: 'Lei 13.709/2018 - Lei Geral de Proteção de Dados - Parte III', type: 'pdf' },
            { date: '2025-10-13', subject: 'Raciocínio Lógico-Matemático', lesson: '16', topic: 'Geometria Espacial', type: 'pdf' },
            { date: '2025-10-13', subject: 'Conhecimentos Específicos', lesson: '45', topic: 'Educação Corporativa TD&E e Planejamento', type: 'video' },
            { date: '2025-10-13', subject: 'Conhecimentos Específicos', lesson: '46', topic: 'Educação Corporativa TD&E e Planejamento III', type: 'video' },
            { date: '2025-10-13', subject: 'Conhecimentos Específicos', lesson: '47', topic: 'Educação Corporativa - Conceitos Iniciais', type: 'video' },
            { date: '2025-10-13', subject: 'Conhecimentos Específicos', lesson: '48', topic: 'Educação Corporativa - Organizações de Aprendizagem e Trilha de Aprendizagem', type: 'video' },
            { date: '2025-10-13', subject: 'Conhecimentos Específicos', lesson: '49', topic: 'Educação Corporativa - Organizações de Aprendizagem e Trilha de Aprendizagem II', type: 'video' },
            { date: '2025-10-13', subject: 'Conhecimentos Específicos', lesson: '50', topic: 'Readaptação e Reabilitação', type: 'video' },
            { date: '2025-10-14', subject: 'Raciocínio Lógico-Matemático', lesson: '16', topic: 'Geometria Espacial', type: 'pdf' },
            { date: '2025-10-14', subject: 'Raciocínio Lógico-Matemático', lesson: '17', topic: 'Geometria Analitica', type: 'pdf' },
            { date: '2025-10-14', subject: 'Conhecimentos Específicos', lesson: '51', topic: 'Readaptação e Reabilitação II', type: 'video' },
            { date: '2025-10-14', subject: 'Conhecimentos Específicos', lesson: '1', topic: 'Atuação do Psicólogo no SUAS I', type: 'video' },
            { date: '2025-10-14', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'Atuação do Psicólogo no SUAS II', type: 'video' },
            { date: '2025-10-14', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'Atuação do Psicólogo no SUAS III', type: 'video' },
            { date: '2025-10-15', subject: 'Raciocínio Lógico-Matemático', lesson: '17', topic: 'Geometria Analítica', type: 'pdf' },
            { date: '2025-10-15', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'Atuação do Psicólogo no SUAS III', type: 'video' },
            { date: '2025-10-15', subject: 'Conhecimentos Específicos', lesson: '4', topic: 'Atuação do Psicólogo no SUAS IV', type: 'video' },
            { date: '2025-10-15', subject: 'Conhecimentos Específicos', lesson: '5', topic: 'Atuação do Psicólogo no SUAS V', type: 'video' },
            { date: '2025-10-15', subject: 'Conhecimentos Específicos', lesson: '1', topic: 'Os Direitos Fundamentais da Criança e do Adolescente - Direito à Vida e à Saúde e Direito à Liberdade, Ao Respeito e à Dignidade', type: 'video' },
            { date: '2025-10-15', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'Os Direitos Fundamentais da Criança e do Adolescente - Direito à Convivência Familiar e Comunitária', type: 'video' },
            { date: '2025-10-15', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'Os Direitos Fundamentais da Criança e do Adolescente - Direito à Convivência Familiar e Comunitária II', type: 'video' },
            { date: '2025-10-16', subject: 'Raciocínio Lógico-Matemático', lesson: '18', topic: 'Matrizes, Determinantes e Sistemas Lineares', type: 'pdf' },
            { date: '2025-10-16', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'Os Direitos Fundamentais da Criança e do Adolescente - Direito à Convivência Familiar e Comunitária II', type: 'video' },
            { date: '2025-10-16', subject: 'Conhecimentos Específicos', lesson: '4', topic: 'Os Direitos Fundamentais da Criança e do Adolescente - Resolução de Questões', type: 'video' },
            { date: '2025-10-16', subject: 'Conhecimentos Específicos', lesson: '5', topic: 'As Medidas Específicas de Proteção à Criança e Ao Adolescente', type: 'video' },
            { date: '2025-10-16', subject: 'Conhecimentos Específicos', lesson: '6', topic: 'As Medidas Específicas de Proteção à Criança e Ao Adolescente II', type: 'video' },
            { date: '2025-10-16', subject: 'Conhecimentos Específicos', lesson: '7', topic: 'As Medidas Específicas de Proteção à Criança e Ao Adolescente - Resolução de Questões', type: 'video' },
            { date: '2025-10-16', subject: 'Conhecimentos Específicos', lesson: '8', topic: 'Adolescente Em Conflito Com a Lei e as Medidas Socioeducativas', type: 'video' },
            { date: '2025-10-17', subject: 'Conhecimentos Específicos', lesson: '8', topic: 'Adolescente Em Conflito Com a Lei e as Medidas Socioeducativas', type: 'video' },
            { date: '2025-10-17', subject: 'Conhecimentos Específicos', lesson: '9', topic: 'Adolescente Em Conflito Com a Lei e as Medidas Socioeducativas II', type: 'video' },
            { date: '2025-10-17', subject: 'Conhecimentos Específicos', lesson: '10', topic: 'Adolescente Em Conflito Com a Lei e as Medidas Socioeducativas III - Resolução de Questões', type: 'video' },
            { date: '2025-10-17', subject: 'Conhecimentos Específicos', lesson: '1', topic: 'Resolução CFP 10/2005 - Código de Ética do Psicólogo', type: 'video' },
            { date: '2025-10-17', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'Resolução CFP 10/2005 II - Código de Ética do Psicólogo', type: 'video' },
            { date: '2025-10-18', subject: 'Conhecimentos Específicos', lesson: '2', topic: 'Resolução CFP 10/2005 II - Código de Ética do Psicólogo', type: 'video' },
            { date: '2025-10-18', subject: 'Conhecimentos Específicos', lesson: '3', topic: 'Resolução CFP 10/2005 III - Código de Ética do Psicólogo', type: 'video' },
        ];